// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DownloadantivirusTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void downloadantivirus() {
    // Test name: download-anti-virus
    // Step # | name | target | value
    // 1 | open | https://www.avira.com/ | 
    driver.get("https://www.avira.com/");
    // 2 | setWindowSize | 1089x874 | 
    driver.manage().window().setSize(new Dimension(1089, 874));
    // 3 | click | id=for-home | 
    driver.findElement(By.id("for-home")).click();
    // 4 | click | css=#mo-qa-av-hub > .nav-product-name | 
    driver.findElement(By.cssSelector("#mo-qa-av-hub > .nav-product-name")).click();
    // 5 | click | id=mo-qa-staginghub-1 | 
    driver.findElement(By.id("mo-qa-staginghub-1")).click();
    // 6 | click | css=.download-page-helper__content__text | 
    driver.findElement(By.cssSelector(".download-page-helper__content__text")).click();
    // 7 | close |  | 
    driver.close();
  }
}
