// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NextyearsubjectsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void nextyearsubjects() {
    // Test name: next-year-subjects
    // Step # | name | target | value
    // 1 | open | /es/ | 
    driver.get("https://www.uah.es//es/");
    // 2 | setWindowSize | 1089x874 | 
    driver.manage().window().setSize(new Dimension(1089, 874));
    // 3 | click | linkText=Grados | 
    driver.findElement(By.linkText("Grados")).click();
    // 4 | click | id=tab-Ingenieria-y-Arquitectura | 
    driver.findElement(By.id("tab-Ingenieria-y-Arquitectura")).click();
    // 5 | click | linkText=Grado en Ingeniería de Computadores | 
    driver.findElement(By.linkText("Grado en Ingeniería de Computadores")).click();
    // 6 | click | id=tab-planificacion-de-la-ensenanza | 
    driver.findElement(By.id("tab-planificacion-de-la-ensenanza")).click();
    // 7 | click | linkText=Asignaturas, profesorado y guías docentes (nuevo 2019-20) | 
    driver.findElement(By.linkText("Asignaturas, profesorado y guías docentes (nuevo 2019-20)")).click();
    // 8 | click | css=.layout-container:nth-child(2) .col-xs-12 | 
    driver.findElement(By.cssSelector(".layout-container:nth-child(2) .col-xs-12")).click();
    // 9 | click | css=.layout-container:nth-child(2) .col-xs-12 | 
    driver.findElement(By.cssSelector(".layout-container:nth-child(2) .col-xs-12")).click();
    // 10 | close |  | 
    driver.close();
  }
}
